### ISSUE TITLE
[Feature Request] Add a Preview Button to the Headerbar

### ISSUE THREAD

**Issue by rusty-snake** [UberWriter/uberwriter#124]
Add a Button to open (or close) the Preview to the Headerbar.
Mockup:
![Mockup](https://gist.githubusercontent.com/rusty-snake/11710bb195895c35f20244d98967adc4/raw/b312f8d0b80d11847b28b309220a14292065628d/preview_preview-fs8.png)
 (or toggel the position of preview and save)

If you have to switch between preview and source frequently, it is so much easier, because only one click is needed to open the preview.

**Comment by somas95** [comment]
I've been thinking about this. We've changed the position of the Preview/Focus Mode/Fullscreen a couple times now. 
Some options are:

- The current approach
- The former approach (similar to the one we have now, but with three symbolic icons in a row, at the top of the menu)
- The former-former approach, three labels always accessible at the bottom left of the window

And the one you suggest. I'll add some variations:

- Preview and focus mode labeled buttons at the headerbar, and an iconic fullscreen button along with the close button
- The same but with symbolic icons for preview and focus mode too

Pros of the later: smaller buttons, less cluttered headerbar
Cons: Almost every button in the headerbar is a labeled one, so that would break consistency. I'll do some quick mockups to see how all these options look

**Comment by somas95** [comment]
I came across with this mockup. Now that we can have tooltips on the popovers I feel right about putting symbolic icons in it

![image](https://user-images.githubusercontent.com/8913975/55324789-6ac11b00-5483-11e9-99e8-efbe94673f09.png)

The tooltips will make everything clear, but the symbolic icons in the popover are for focus mode, hemingway mode and fullscreen mode respectively.

What do you think about this approach, @bertob? I'm still struggling finding a good design. This one kinda follows gedit's one, but maybe the right side is overcluttered. We could move the save button to the left and have all the file-management related buttons at the left, and the file-editing ones at the right, with the exception of the preview button. I searched the GNOME HIG page, and didn't found clear guidelines regarding elements distribution, so any suggestion is welcome

**Comment by bertob** [comment]
@somas95 Yeah, this is not easy. Since we have no real data, the best we can do is make an educated guess as to which features people likely access the most, and putting those front and center :)

If this includes Preview and Fullscreen, perhaps they should be in the header bar, and perhaps some of the things currently in the header bar could be de-emphasized or moved to the primary menu.

Here's a quick experiment:

![image](https://user-images.githubusercontent.com/1908896/56033273-87cbd880-5d24-11e9-857f-0404c3ba65d7.png)

**Comment by somas95** [comment]
Mmmm... Having the search function inside a menu is kinda strange for me, but it could work. 
It's worth noticing that in the next version there will be a new mode (Hemingway mode), so that's another switch in the menu. That's why I thought in putting the three modes in a row inside the menu. Lollypop does something similar 

I also thought on keeping the switches, but inside another menu. I don't quite like it 

More ideas to clean the interface: 

- Merge "save as" and "export" dialogs? I don't like this idea 
- Move "save as" and "export" entries to a popover near "save". That popover would have an entire for "save as", "pdf", "html", etc, with different dialogs for each of those entries

**Comment by somas95** [comment]
I came across with this quick mockup. It shows the idea from #111 too
![mockup](https://user-images.githubusercontent.com/8913975/56095747-2b151d00-5ee0-11e9-83c4-faa7ffda95ca.png)

**Comment by goncalossilva** [comment]
One nice thing about having the options inside the menu is that it's super clear what they do. At the moment all options are text-based, except for search/menu, whose icons are pretty ubiquitous.

I'm quite fond of the mockup you have there though, and I agree that preview deserves more spotlight.

**Comment by somas95** [comment]
Solved with e38520c35dc05d86958252f1416329d1e1ba8f13
