### ISSUE TITLE
Builder fails to build Flatpak (/bin/sh: flatpak-builder: command not found)

### ISSUE THREAD

**Issue by alex285** [UberWriter/uberwriter#166]
**Reproduce**
1. Open GNOME Builder
2. Clone UberWriter
3. Press Build

**Output:**
```
flatpak build --share=network --nofilesystem=host --filesystem=/home/me/.var/app/org.gnome.Builder/cache/gnome-builder --filesystem=/home/me/Git/Apps/uberwriter --filesystem=/home/me/Git/Apps/uberwriter --env=NOCONFIGURE=1 /home/me/.var/app/org.gnome.Builder/cache/gnome-builder/projects/uberwriter/flatpak/staging/x86_64-master make
cd flatpak; flatpak-builder --force-clean --install --user _build uberwriter.json
/bin/sh: flatpak-builder: command not found
make: *** [Makefile:4: flatpak-user-install] Error 127
```

I have `flatpak-builder` already installed, but originally i had the Flatpak package `org.flatpak.Builder` that is mostly likely the case on people with Silverblue

**Comment by alex285** [comment]
actually the issue is different;  can we have a compatible Flatpak build directly from Builder?

**Comment by refi64** [comment]
Ah I see the issue now, UberWriter doesn't use any of the build systems Builder supports, but Builder sees the Makefile and assumes it's how the project should be built. Make in its helpfulness (/s) runs the first target defined, which in this case is flatpak-user-install.

So I guess the issue here is twofold:

- The Makefile should probably define another target first to let the user know what it's intent is for.
- Up to the maintainers would be adding support for a Builder-friendly workflow (if you actually want the best Builder support I think this would probably involve Meson somehow?).

**Comment by BrainBlasted** [comment]
Should be fixed now that [meson](https://github.com/UberWriter/uberwriter/pull/168) is used.

**Comment by somas95** [comment]
True. Closing it now
